### ISSUE TITLE
bedrock-identity does not validate a proper key pair

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-identity#2]
I have composed a test which demonstrates the issue: https://github.com/digitalbazaar/bedrock-identity/compare/2.x...test

The test output shows:

```
PLAINTEST <Buffer 70 6c 61 69 6e 74 65 78 74>
DECRYPTED <SlowBuffer 70 6c 61 69 6e 74 65 78 74>
```

It appears the issue seems to be that a SlowBuffer is being compared with a Buffer and although the contents are the same, the equality test is failing.

The test branch also includes a library [node-buffertools](https://github.com/bnoordhuis/node-buffertools) which is able to accurately compare these two data types.

**Comment by davidlehn** [comment]
I added a patch using the simpler https://github.com/substack/node-buffer-equal module since we just need the one function and only until we drop node 0.10.x support.
https://github.com/digitalbazaar/bedrock-identity/commit/5e46cf83de89e78fda4c80489df84c4bd278150d

We should clean up the test branch and merge it into 2.x:  remove comments, rename _checkKeyPair to api.checkKeyPair and avoid the wrapper, and perhaps avoid `dropCollections.onInit = true` (it was causing issues for me).

**Comment by mattcollier** [comment]
This has been completed.
